name: PlannerBuild

env:
  main_project_module: app

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y.%m.%d.%k.%M')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: gradle assembleDebug

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.repository_name }} - ${{ env.date_today }}
          tag_name: d/${{ env.date_today }}
          prerelease: false
          files: ${{ env.main_project_module }}/build/outputs/apk/debug/app-debug.apk
